# Generated by Django 5.2.6 on 2025-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acceptcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_caartid', models.CharField(default='', max_length=120)),
                ('created_at', models.CharField(default='', max_length=150)),
                ('status', models.CharField(default='New', max_length=120)),
                ('product_name', models.CharField(default='', max_length=120)),
                ('total', models.CharField(default='', max_length=120)),
                ('quantity', models.CharField(default='', max_length=120)),
                ('price_per_kg', models.CharField(default=0, max_length=120)),
                ('note', models.CharField(default='Note', max_length=12000)),
                ('customer_name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('image_1', models.ImageField(upload_to='cart/')),
                ('fromm', models.CharField(default='', max_length=12000)),
                ('to', models.CharField(default='', max_length=12200)),
            ],
        ),
        migrations.CreateModel(
            name='farmerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('category', models.CharField(default='', max_length=120)),
                ('amount', models.CharField(default='', max_length=120)),
                ('per_unit', models.CharField(default='', max_length=120)),
                ('available_quantity', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=2200)),
                ('address', models.CharField(default='', max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='farmmprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(default='', upload_to='')),
                ('username', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=120)),
                ('farmname', models.CharField(default='', max_length=120)),
                ('location', models.CharField(default='', max_length=2200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
