# Generated by Django 5.2.6 on 2025-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acceptedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('status', models.CharField(default='', max_length=120)),
                ('created_at', models.CharField(default='', max_length=150)),
                ('transporter_name', models.CharField(default='', max_length=120)),
                ('customer_name', models.CharField(default='', max_length=120)),
                ('quantity', models.CharField(default='', max_length=120)),
                ('price_per_kg', models.CharField(default=0, max_length=120)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('image_1', models.ImageField(upload_to='cart/')),
                ('fromm', models.CharField(default='', max_length=12000)),
                ('to', models.CharField(default='', max_length=12200)),
                ('accept_cart_id', models.CharField(default='', max_length=2200)),
                ('accept_order_id', models.CharField(default='', max_length=2200)),
            ],
        ),
    ]
