# Generated by Django 5.2.6 on 2025-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_uploads', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=125)),
                ('occupation', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=140)),
                ('phone_no', models.CharField(max_length=140)),
                ('date', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
