# Generated by Django 3.2.25 on 2025-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20250813_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(default='', upload_to='')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=220)),
                ('date', models.CharField(default='', max_length=220)),
            ],
        ),
    ]
